import Link from "next/link";
import { ArrowUpRight, BookOpen, Code2, HeartHandshake, ShieldCheck, UsersRound } from "lucide-react";
import { PublicCtaBand, PublicHero } from "@/components/PublicStory";

const tracks = [
  ["Academic & STEM tutor", "Share subject-matter expertise where a privately reviewed community-learning opportunity is available.", BookOpen],
  ["Technical mentor", "Offer technical perspective relevant to carefully scoped learning and creative-development activities.", Code2],
  ["Community coordinator", "Support appropriate community activities through coordination reviewed by the foundation team.", UsersRound],
  ["Safeguarding specialist", "Provide safeguarding-aware perspective for approved initiatives when requested by the foundation team.", ShieldCheck],
];

export default function VolunteerPage() {
  return <div className="bg-[#FCFCFA]"><PublicHero eyebrow="Community & mentorship" title="Offer what you know, through the right pathway." intro="Explore appropriate ways to share relevant expertise through PWLIF’s private, review-based partnership process." primaryAction={{ href: "/support", label: "Contact the foundation" }} />
    <section className="px-5 py-16 sm:px-8 sm:py-24 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#079432]">Possible contribution areas</p><h2 className="mt-4 font-montserrat text-4xl font-black tracking-[-0.05em] text-[#0B2E6B]">Expertise with care at its centre.</h2><p className="mt-5 text-base leading-8 text-[#0B2E6B]/70">Volunteer and mentorship arrangements are considered privately when an appropriate opportunity is available.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{tracks.map(([title, description, Icon]) => { const TrackIcon = Icon as typeof BookOpen; return <article key={title as string} className="group flex min-h-64 flex-col justify-between rounded-[1.75rem] border border-[#0B2E6B]/10 bg-white p-8 shadow-[0_14px_40px_rgba(11,46,107,0.07)] transition hover:-translate-y-1 hover:border-[#079432]/35"><div><TrackIcon className="h-7 w-7 text-[#079432]" /><h3 className="mt-10 font-montserrat text-2xl font-black tracking-[-0.04em] text-[#0B2E6B]">{title as string}</h3><p className="mt-4 text-sm leading-7 text-[#0B2E6B]/70">{description as string}</p></div><span className="mt-8 text-[10px] font-bold uppercase tracking-[0.13em] text-[#079432]">Foundation-reviewed pathway</span></article>; })}</div><div className="mt-16 rounded-[2rem] bg-[#EAF7EF] p-8 sm:p-12"><HeartHandshake className="h-8 w-8 text-[#079432]" /><h2 className="mt-7 font-montserrat text-3xl font-black tracking-[-0.04em] text-[#0B2E6B]">Volunteer applications are not collected here.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-[#0B2E6B]/70">PWLIF does not collect volunteer applications or contact details through this site. Use the foundation contact route for a general enquiry, and the team will guide any appropriate next step.</p><Link href="/support" className="mt-7 inline-flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.12em] text-[#079432] hover:underline">Contact the foundation <ArrowUpRight className="h-4 w-4" /></Link></div></div></section><PublicCtaBand eyebrow="Have a relevant question?" title="Begin with a general enquiry." intro="The foundation will guide any suitable conversation through the appropriate route." action={{ href: "/support", label: "Contact PWLIF" }} /></div>;
}
