"use client";

import Link from "next/link";
import { ArrowUpRight, ShieldCheck } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { PublicCtaBand, PublicHero, SectionHeading } from "@/components/PublicStory";

export default function MeetTheTeamPage() {
  const { teamMembers } = useAuth();
  return <div className="bg-[#FCFCFA]">
    <PublicHero dark eyebrow="Leadership and advisory" title="The people holding space for potential." intro="A growing community of youth advocates, educators, mentors, and foundation leaders guides the work of Potential Without Limits International Foundation." primaryAction={{ href: "/volunteer", label: "Explore volunteer pathways" }} />
    <section className="px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-[92rem]"><SectionHeading eyebrow="The people behind the work" title="Leadership, expertise, and a shared sense of responsibility." intro="Profile details and photographs are displayed only when they have been approved for public visibility." /><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">{teamMembers.map((member, index) => <article key={member.id} className="group overflow-hidden rounded-[1.75rem] bg-white shadow-[0_16px_44px_rgba(11,46,107,0.09)]"><div className="relative aspect-square overflow-hidden bg-[#0B2E6B]">{member.visibility?.showPhoto !== false && member.photoUrl ? <img src={member.photoUrl} alt={member.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /> : <div className="flex h-full w-full items-center justify-center bg-[radial-gradient(circle_at_20%_20%,rgba(20,184,74,0.36),transparent_30%),linear-gradient(135deg,#061D45,#0B2E6B)]"><ShieldCheck className="h-12 w-12 text-white/70" /></div>}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#061D45]/78 to-transparent p-5"><span className="font-montserrat text-4xl font-black text-white/55">{String(index + 1).padStart(2, "0")}</span></div></div><div className="p-6"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#079432]">{member.role || "Foundation leadership"}</p><h2 className="mt-3 font-montserrat text-2xl font-black tracking-[-0.035em] text-[#0B2E6B]">{member.name}</h2>{member.bio && <p className="mt-4 whitespace-pre-line text-sm leading-6 text-[#0B2E6B]/65">{member.bio}</p>}{member.linkedinUrl && <a href={member.linkedinUrl} target="_blank" rel="noopener noreferrer" aria-label={`Open ${member.name}'s professional social profile`} className="mt-7 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.12em] text-[#079432] hover:text-[#14B84A]">Professional social profile <ArrowUpRight className="h-4 w-4" /></a>}</div></article>)}</div>{teamMembers.length === 0 && <div className="mt-10 rounded-[1.75rem] border border-dashed border-[#0B2E6B]/18 p-10 text-sm text-[#0B2E6B]/64">Leadership profiles will appear here when they are approved for public display by a PWLIF administrator.</div>}</div></section>
    <PublicCtaBand eyebrow="Share your expertise" title="Interested in supporting a considered foundation journey?" intro="PWLIF can discuss appropriate volunteer, mentorship, and advisory pathways through a private orientation conversation." action={{ href: "/volunteer", label: "Explore volunteer pathways" }} />
  </div>;
}
