"use client";

import Script from "next/script";
import { FormEvent, useState } from "react";

const blank = { fullName: "", email: "", organization: "", roleTitle: "", websiteOrLinkedIn: "", orgDescription: "", supportIntent: "", preferredContactWindow: "", consent: false, website: "" };

export function OrientationForm({ bookingUrl }: { bookingUrl: string }) {
  const [form, setForm] = useState(blank);
  const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle");
  const [message, setMessage] = useState("");
  async function submit(event: FormEvent) {
    event.preventDefault(); setState("sending"); setMessage("");
    const response = await fetch("/api/orientation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }).catch(() => null);
    const payload = response ? await response.json().catch(() => null) : null;
    if (!response?.ok) { setState("error"); setMessage(payload?.error ?? "We could not submit your request. Please try again."); return; }
    setState("success"); setMessage("");
  }
  if (state === "success") return <section className="rounded-3xl border border-[#079432]/20 bg-white p-5 shadow-xl shadow-[#0B2E6B]/5 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[#079432]">Request received</p><h2 className="mt-2 font-montserrat text-3xl font-black tracking-tight text-[#0B2E6B]">Choose an orientation time.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#0B2E6B]/70">Your request has been saved privately. You can now choose a time for an introductory conversation; this is not a sponsorship commitment.</p><div className="mt-6 min-h-[700px] overflow-hidden rounded-2xl border border-[#0B2E6B]/10"><div className="calendly-inline-widget h-[700px] min-w-[320px]" data-url={bookingUrl} /></div><Script src="https://assets.calendly.com/assets/external/widget.js" strategy="afterInteractive" /></section>;
  const update = (key: keyof typeof blank, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const input = "mt-1 w-full rounded-xl border border-[#0B2E6B]/15 bg-[#FCFCFA] px-3 py-3 text-sm outline-none transition focus:border-[#079432] focus:ring-4 focus:ring-[#079432]/10";
  return <form onSubmit={submit} className="rounded-3xl border border-[#0B2E6B]/10 bg-white p-5 shadow-xl shadow-[#0B2E6B]/5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Full name*<input required value={form.fullName} onChange={(e) => update("fullName", e.target.value)} className={input} /></label><label className="text-sm font-bold">Email address*<input required type="email" value={form.email} onChange={(e) => update("email", e.target.value)} className={input} /></label><label className="text-sm font-bold">Organisation*<input required value={form.organization} onChange={(e) => update("organization", e.target.value)} className={input} /></label><label className="text-sm font-bold">Role or title*<input required value={form.roleTitle} onChange={(e) => update("roleTitle", e.target.value)} className={input} /></label></div><label className="mt-5 block text-sm font-bold">Website or LinkedIn URL*<input required type="url" placeholder="https://" value={form.websiteOrLinkedIn} onChange={(e) => update("websiteOrLinkedIn", e.target.value)} className={input} /></label><label className="mt-5 block text-sm font-bold">What does your organisation do?*<textarea required rows={4} value={form.orgDescription} onChange={(e) => update("orgDescription", e.target.value)} className={input} /></label><label className="mt-5 block text-sm font-bold">How would you like to explore support?*<textarea required rows={4} value={form.supportIntent} onChange={(e) => update("supportIntent", e.target.value)} className={input} /></label><label className="mt-5 block text-sm font-bold">Preferred contact window <input value={form.preferredContactWindow} onChange={(e) => update("preferredContactWindow", e.target.value)} className={input} /></label><input aria-hidden="true" tabIndex={-1} autoComplete="off" className="hidden" value={form.website} onChange={(e) => update("website", e.target.value)} /><label className="mt-5 flex items-start gap-3 text-sm leading-5 text-[#0B2E6B]/75"><input required type="checkbox" checked={form.consent} onChange={(e) => update("consent", e.target.checked)} className="mt-1 h-4 w-4 accent-[#079432]" />I agree that PWLIF may use these details only to respond to this orientation request.</label>{state === "error" && <p role="alert" className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-800">{message}</p>}<button disabled={state === "sending"} className="mt-6 rounded-xl bg-[#079432] px-5 py-3 text-xs font-black uppercase tracking-wider text-white transition hover:bg-[#004b20] disabled:opacity-60">{state === "sending" ? "Saving request…" : "Request Sponsor Orientation"}</button></form>;
}
