import { HeartHandshake, ShieldCheck } from "lucide-react";
import { PublicCtaBand, PublicHero } from "@/components/PublicStory";

const pathways = [
  ["Sponsor Talent", "Orientation required", "Discuss Sponsor Talent opportunities, appropriate boundaries, and the orientation process before any partnership decision."],
  ["Learning & mentorship", "Private discussion", "Explore how learning, mentorship, and community-informed opportunities may be considered through appropriate channels."],
  ["Foundation introduction", "By orientation", "Request an introduction to learn more about PWLIF’s approach and whether a future conversation is appropriate."],
];

export default function DonatePage() {
  return <div className="bg-[#FCFCFA]"><PublicHero dark eyebrow="Partnership & support" title="Support begins with an appropriate conversation." intro="PWLIF does not accept or process financial contributions through this website. Partnership conversations begin with a private orientation request." primaryAction={{ href: "/book-a-call", label: "Request orientation" }} />
    <section className="px-5 py-16 sm:px-8 sm:py-24 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-5 md:grid-cols-3">{pathways.map(([eyebrow, title, description], index) => <article key={eyebrow} className={`flex min-h-80 flex-col justify-between rounded-[1.75rem] border p-8 ${index === 0 ? "border-[#079432]/35 bg-[#EAF7EF]" : "border-[#0B2E6B]/10 bg-white"}`}><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#079432]">{eyebrow}</p><h2 className="mt-10 font-montserrat text-3xl font-black tracking-[-0.05em] text-[#0B2E6B]">{title}</h2><p className="mt-5 text-sm leading-7 text-[#0B2E6B]/70">{description}</p></div><span className="mt-9 text-[10px] font-bold uppercase tracking-[0.13em] text-[#0B2E6B]/52">No online contribution available</span></article>)}</div><div className="mt-16 grid gap-8 rounded-[2rem] bg-[#061D45] p-8 text-white sm:p-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><HeartHandshake className="h-10 w-10 text-[#F7B500]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#A9F1C3]">Financial boundary</p><h2 className="mt-4 font-montserrat text-3xl font-black tracking-[-0.04em]">Financial contributions are not available online.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-white/70">Online donations, payment collection, tax receipts, and financial reporting are intentionally unavailable through this portal. Appropriate information is discussed only through private, review-based conversations.</p><div className="mt-8 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.13em] text-[#A9F1C3]"><ShieldCheck className="h-4 w-4" />Safeguarding-aware pathway</div></div></div></div></section><PublicCtaBand eyebrow="Begin privately" title="Explore a responsible partnership pathway." intro="Request an orientation before any deeper sponsorship or support conversation." action={{ href: "/book-a-call", label: "Request orientation" }} /></div>;
}
